## 인덱싱, 슬라이싱

In [2]:
import numpy as np

In [2]:
narray = np.arange(5)
narray

array([0, 1, 2, 3, 4])

In [6]:
print(narray[1], narray[-1]) # 음수가 붙으면 뒤에서 n번째 
print(narray[1:])
print(narray[1:5])
print(narray[:])
print(narray[2:4]) 

1 4
[1 2 3 4]
[1 2 3 4]
[0 1 2 3 4]
[2 3]


In [ ]:
'''
    2차원 배열에서의 인덱싱과 슬라이싱을 다뤄본다. 
    인덱스는 [ . ] 콤마를 기준으로 2 개의 인자를 받는다. 
    앞 인자값은 행의 index 
    뒤 인자값은 열의 index
    , 없이 : 를 넣으면 모든것을 다 포함한다. 
'''

In [33]:
np.random.seed(100)
narray1 = np.random.randint(0,20,16).reshape(4,4)
narray1

array([[ 8,  3,  7, 15],
       [16, 10,  2,  2],
       [ 2, 14,  2, 17],
       [16, 15,  4, 11]])

In [44]:
# 1. narray1 에서 첫번쨰 줄 7을 가져오려면
narray1[0,2]
narray1[0][2]

# 2. 두번쨰 라인    [16, 10,  2,  2],
narray1[1,:]
narray1[1][:]
narray1[1:2,:] # 2차원 출력됨


# 3. 전체 행에 대해서 4번쨰 열만 다 가져오려면
narray1[:,3]
narray1[:,3:]

# 4. 전체행에 대해서 1,2 번쨰 열만 다 가져오려면
narray1[:,:2]


array([[ 8,  3],
       [16, 10],
       [ 2, 14],
       [16, 15]])

### 인덱싱과 조건 슬라이서 

In [48]:
np.random.seed(0)
arr3 = np.random.randn(4,4)
print(arr3)
print(type(arr3))

[[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351]
 [ 0.76103773  0.12167502  0.44386323  0.33367433]]
<class 'numpy.ndarray'>


In [51]:
# 1. 논리연산자 사용
arr3[arr3<0]

# 2. 0보다 작은 값들을 전부 전부 0 으로 치환
arr3[arr3<0] =0
arr3 # 원본도 같이 바뀐다. 

array([[1.76405235, 0.40015721, 0.97873798, 2.2408932 ],
       [1.86755799, 0.        , 0.95008842, 0.        ],
       [0.        , 0.4105985 , 0.14404357, 1.45427351],
       [0.76103773, 0.12167502, 0.44386323, 0.33367433]])

In [53]:
# 3. where 함수 
'''
    arr3가 0보다 크면 arr3를 그대로 리턴 
    arr3 가 0보다 작으면 -1을 리턴 
'''

arr3_1 = np.where(arr3>0, arr3, -1)
arr3_1

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -1.        ,  0.95008842, -1.        ],
       [-1.        ,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433]])

In [59]:
a= np.array([[1,2],[3,4],[5,6]])
bool_a = (a>2)
print(bool_a)

print(a[bool_a])
print(a[True])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[[[1 2]
  [3 4]
  [5 6]]]


## Numpy 통계함수

In [3]:
arr4 = np.random.randint(0,20,16).reshape(4,4)
arr4

array([[10, 16,  5, 13],
       [15,  3,  6, 17],
       [ 3,  6, 13, 11],
       [ 6, 18, 18,  1]])

In [ ]:
'''
    Numpy 배열의 통계함수
    sum(), mean(), min(), max(), argmin(), argmax(), cumsum()
'''

In [4]:
print(np.sum(arr4))
print(np.sum(arr4,axis=0)) # 행의 i열을 다 더한값을 리턴
print(np.sum(arr4,axis=1)) # 열의 i 행을 다 더한값을 리턴 
print('#'*50)
print(np.cumsum(arr4, axis=0))
print('#'*50)
print(np.cumsum(arr4, axis=1))
print('#'*50)
'''
    axix =0
    모든 행들을 다 검색 
    그 중 가장 큰 값의 인덱스를 리턴
'''
print(np.argmax(arr4, axis=0))

161
[34 43 42 42]
[44 41 33 43]
##################################################
[[10 16  5 13]
 [25 19 11 30]
 [28 25 24 41]
 [34 43 42 42]]
##################################################
[[10 26 31 44]
 [15 18 24 41]
 [ 3  9 22 33]
 [ 6 24 42 43]]
##################################################
13
